# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://cheapy-ofertas.github.io/landing-page
title: Cheapy
email: cheapy.ispp@gmail.com
author: Cheapy 2021
description: >  
  Cheapy se trata de una aplicación web que ofrece descuentos poco comunes a los clientes de bares y restaurantes.
copyright: 'Copyright &copy; 2021 Cheapy. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Web
    url: https://cheapy-ofertas.herokuapp.com
  - title: github
    url: https://github.com/cheapy-ofertas
  - title: gmail
    url: mailto:cheapy.ispp@gmail.com
